---
title: "L01 Review"
subtitle: "Data Science 3 with R (STAT 301-3)"
author: "Judy Zeng"
pagetitle: "L01 Judy Zeng"
date: today

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    code-fold: false
    link-external-newwindow: true

execute:
  warning: false

from: markdown+emoji
reference-location: margin
citation-location: margin   
---

::: {.callout-tip icon="false"}
## Github Repo Link

[GitHub Link](https://github.com/stat301-3-2026-spring/l01-review-judyfzeng.git)
:::

## Overview

The goal of this lab is to review machine learning/predictive modeling vocabulary and concepts covered in Data Science 2 with R (STAT 301-2).

## Questions

When completing the following questions ensure your solutions are neatly formatted and clearly indicated. Consider including diagrams/images in some of your solutions, if it helps to make things easier to describe/discuss.

### Question 1

Provide a brief outline/overview of the steps involved in a supervised machine learning process. Could provide this as a bulleted list. 

::: {.callout-tip icon="false"}
## Solution

- Data cleaning & EDA
- Split training/testing data & set up resampling folds
- Create recipes / feature engineering
- Build hyperparameter tuning grids
- Fit/tune models
- Evaluate performance to identify best model
- Fit best model on test data & evaluate performance

:::

### Question 2

Explain the difference between supervised and unsupervised learning.

::: {.callout-tip icon="false"}
## Solution

Supervised learning has a target variable and outcome of interest while unsupervised learning has no target variable and instead extracts structure from the data.

:::

### Question 3 

In general, we can classify a model by its purpose into 1 of the 3 categories below. Provide a brief description of the goals of these model classes.

#### Descriptive Models 

::: {.callout-tip icon="false"}
## Solution

Descriptive models identify patterns, trends, and relationships in the data. 

:::

#### Inferential Models

::: {.callout-tip icon="false"}
## Solution

Inferential models evaluates how variable x affects target outcome y (aka find the causal effect of x on y).

:::

#### Predictive Models

::: {.callout-tip icon="false"}
## Solution

Predictive models predict target outcome y given predictors x.

:::

### Question 4 

We can further describe/classify predictive models by how they were derived or developed as being either mechanistic or empirically driven. 

#### Part (a)

What does it mean to be a mechanistic model?

::: {.callout-tip icon="false"}
## Solution

A mechanistic model assumes an underlying formula or structure in order to predict the outcome variable.

:::

#### Part (b)

What does it mean to be an empirically driven model?

::: {.callout-tip icon="false"}
## Solution

An empirically driven model does not assume any underlying formula or structure, and instead relies on patterns in the data to predict the outcome variable.

:::

#### Part (c)

How does the mechanistic and empirically driven model terminology relate to the parametric and nonparametric model terminology? 

::: {.callout-tip icon="false"}
## Solution

Mechanistic model is used interchangeably with parametric model. Empirically driven model is used interchangeably with nonparametric model.

:::

#### Part (d)

In general, is a mechanistic or empirically driven model easier to interpret? Explain.

::: {.callout-tip icon="false"}
## Solution

Mechanistic model is easier to interpret because the model is built on established theories and formulas.

:::

#### Part (e)

How does mechanistic and empirically driven model terminology relate to the idea of model flexibility? That is, which would be more or less flexible than the other.

::: {.callout-tip icon="false"}
## Solution

Empirically driven models are more flexible because there is no underlying formula and assumptions limiting the prediction outcomes and interpretations. These models can fit to complex patterns in the data.

:::

#### Part (f)

Describe the bias-variance trade-off when considering the use of a mechanistic or empirically driven model. 

::: {.callout-tip icon="false"}
## Solution

Mechanistic models are more biased (as the underlying formula may be overly simplistic) but have lower variance (as these models are robust to small changes in the training data). 

Empirically driven models have lower bias (because they are more flexible and fit to the patterns in the data) but higher variance (as these models tend to overfit the data). 

:::

### Question 5 

Explain the difference between a regression and classification machine learning (ML) problems.

::: {.callout-tip icon="false"}
## Solution

Regression problems predict a continuous variable outcome while classification problems predict a categorical variable outcome.

:::

### Question 6 

When splitting the data, why is it useful to stratify by the outcome/target variable? 

::: {.callout-tip icon="false"}
## Solution

Stratifying by the outcome variable ensures the training and testing data contain balanced class proportions / distribution and prevents bias. For heavily imbalanced or skewed data, there might be a chance that the minority class is underrepresented or unrepresented in one of the data splits, which biases the model.

:::

### Question 7 

Briefly describe how v-fold cross validation with repeats is used to estimate test RMSE. Also provide an explanation of why we use it. 

::: {.callout-tip icon="false"}
## Solution

V-fold cross validation splits the training data into V subsets (aka folds) and use V-1 folds as training data and the remaining fold as the testing data to evaluate the performance of the model. This is repeated until all the folds have served as testing data. Then this entire process is repeated for however many repeats is specified. 

The final performance result is the average of all the fitted and evaluated models. We use V-fold cross validation to ensure the model performance estimates are reliable. 

:::

### Question 8

When might we use a bootstrap resampling procedure instead of v-fold cross validation to estimate test RMSE?

::: {.callout-tip icon="false"}
## Solution

Bootstrap resampling is preferred when the dataset is small. V-fold cross validation might leave too few samples in each fold for accurate and reliable model performance estimates. 

:::

### Question 9 

Briefly describe model tuning and why we use it.

::: {.callout-tip icon="false"}
## Solution

Model tuning is the process of evaluating the performance of different hyperparameter values in a model. 

We use model tuning to identify the best hyperparameters for each model for the given prediction problem.

:::

### Question 10 

What are two common performance metrics when dealing with a regression ML problem?

::: {.callout-tip icon="false"}
## Solution

RMSE and MAE. 

:::

What are two common performance metrics when dealing with a classification ML problem?

::: {.callout-tip icon="false"}
## Solution

ROC AUC and accuracy.

:::

### Question 11

Classify each question/problem below as either prediction or inferential. Explain your reasoning for each.

A company with a subscription based service (for example Netflix, Disney+, New York Times, etc) has data concerning customer interactions with a them, including features like the number of customer service calls, quality of service calls, subscription length, engagement with the service, discounted service, etc. They are interested in two questions:

1. Does a high number of service calls impact a customer's likelihood of churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

Inferential because it wants to evaluate whether there is a causal effect of service calls on customer likelihood. 

:::

2. How likely is it that a customer will churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

Prediction because this question wants to predict a specific value for the outcome of interest (ie. customer churn likelihood). 

:::

